run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - ifElseChain
  gosec:
    severity: medium
    confidence: medium
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unused-parameter
        severity: warning

issues:
  max-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gocyclo
        - gosec
        - gocritic
        - prealloc